# Generated by Django 4.2.27 on 2026-02-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0091_fix_documenttype_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGDocumentVersionSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rag_synced', models.BooleanField(default=False, verbose_name='RAG synced')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Last synced')),
                ('document_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_sync', to='documents.documentversion', verbose_name='Document version')),
            ],
            options={
                'verbose_name': 'RAG document version sync',
                'verbose_name_plural': 'RAG document version syncs',
                'ordering': ('document_version',),
            },
        ),
    ]
